spring:
  application:
    name: internship

server:
  address: 0.0.0.0
  port: ${APPLICATION_PORT}

# ====================== Database Configuration ======================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/internship?createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

# ====================== JPA / Hibernate ======================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

# ====================== JWT Configuration ======================
jwt:
  secret-key: ${JWT_SECRET_KEY}

# ====================== SMTP Configuration ======================
# spring:
#   mail:
#     host: ${SMTP_HOST}
#     port: ${SMTP_PORT}
#     username: ${SMTP_EMAIL}
#     password: ${SMTP_PASSWORD}
#     properties:
#       mail:
#         smtp:
#           auth: true
#           starttls:
#             enable: true
